### ISSUE TITLE
NEXT updates?

### ISSUE THREAD

**Issue by number5** [hhrhhr/luaNMS#1]
Thanks for the great work!

Any chance updating if for the just released NEXT updates?

**Comment by hhrhhr** [comment]
Now I do not already have this game. But all scripts work with unpacked .exml of any version of the game, so if you can unpack the files specified in the readme.txt (and if MBINCompiler began to support this update), then I see no problems with updating the database.

**Comment by number5** [comment]
I don't have access to the PC version either, I only have it on PS4.
